name: SimpleVault
version: 1.0
main: me.hai.simplevault.Main
api-version: 1.21
author: HaiDz
description: Plugin hut vat pham khi dao

commands:
  kho:
    description: Mo kho ca nhan
    usage: /kho

permissions:
  simplevault.admin:
    description: Xem kho nguoi khac
    default: op
